src/WeakRefStrings.jl
test/runtests.jl

Because it's a pointer index, and calls to `pointer` are zero-indexed, "no offset" should be 1, rather than zero. Correct the two-argument constructor to reflect this.
Closes #8

Correct default value of WeakRefString.ind

---

src/WeakRefStrings.jl
test/runtests.jl

I've added `push!()`, because `DataFrames.streamto!()` method gave the following exception while trying to load the data from `.csv`:
```
MethodError: no method matching push!(::WeakRefStrings.WeakRefStringArray{WeakRefString{UInt8},1}, ::WeakRefString{UInt8})
Closest candidates are:
push!(::Any, ::Any, ::Any) at abstractarray.jl:1935
push!(::Any, ::Any, ::Any, ::Any...) at abstractarray.jl:1936
push!(::Array{Any,1}, ::ANY) at array.jl:624
...
Stacktrace:
[1] streamto! at /fs/home/<>/.julia/v0.6/DataFrames/src/abstractdataframe/io.jl:294 [inlined]
[2] macro expansion at /fs/home/<>/.julia/v0.6/DataStreams/src/DataStreams.jl:277 [inlined]
[3] stream!(::CSV.Source{Base.AbstractIOBuffer{Array{UInt8,1}},Nulls.Null}, ::Type{DataStreams.Data.Field}, …
```

Add push!()

---

src/WeakRefStrings.jl

`getindex()` always returns a `String`, never a `WeakRefString`.
See https://github.com/JuliaData/CSV.jl/pull/118#discussion_r153446137.

Stop lying about WeakRefStringArray eltype

---

README.md
src/WeakRefStrings.jl
test/runtests.jl

Remove a few pitfall functions that allowed direct processing of WeakRefStrings. Clarify in docs that WeakRefStrings are for IO optimization and not actual string processing. Cleanup the WeakRefStringArray type parameters and constructors
cc: @nalimilan @alyst: I see this as step one to the plan in https://github.com/JuliaData/CSV.jl/pull/140
Should resolve #19 (@andreasnoack).

Clarify WeakRefStrings purpose

---

src/WeakRefStrings.jl

Addresses an issue where the WeakRefStrings constructors could result in a lockup which required a SIGKILL of the julia process. Note that this addresses only the symptoms of #23.

Reduce number of inner constructors for WeakRefStringArray

---

src/WeakRefStrings.jl
test/runtests.jl

StringArray stores a contiguous buffer of string data and the offset and length for each element in the array. This can be memory mapped to and from disk, and can reduce serialization overhead. This PR also puts iteration back into WeakRefStrings.
cc @andreasnoack

StringArray

---

src/WeakRefStrings.jl

Optimize `setindex` for `StringVector` by special casing 1-d implementation.
Without this patch:
```
julia> using WeakRefStrings, BenchmarkTools
julia> sv = StringVector{String}(convert(Vector{UInt8}, randstring(1024)), UInt64[1:10:1000;], ones(UInt32,100)*9);
julia> @btime for idx in 1:length(sv)
sv[idx] = sv[idx]
end;
45.918 μs (601 allocations: 15.66 KiB)
```
With this:
```
julia> using WeakRefStrings, BenchmarkTools
julia> sv = StringVector{String}(convert(Vector{UInt8}, randstring(1024)), UInt64[1:10:1000;], ones(UInt32,100)*9);
julia> @btime for idx in 1:length(sv)
sv[idx] = sv[idx]
end;
13.610 μs (201 allocations: 6.28 KiB)
```

optimize setindex for StringVector

---

src/WeakRefStrings.jl
test/runtests.jl

Uses intermediary `StringArray{WeakRefString{UInt8}}` for speedup.
ref: https://github.com/JuliaComputing/IndexedTables.jl/pull/166

faster permute! for StringArray{String}

---

src/WeakRefStrings.jl
test/runtests.jl

faster `vcat` for `StringVector`, by direct `vcat` of internal fields and adjusting the offsets.

optimize vcat of StringVector

---

src/WeakRefStrings.jl
test/runtests.jl

I need constructors that have the same signature as the normal ``Array`` constructors for an incoming PR to [TextParse.jl](https://github.com/JuliaComputing/TextParse.jl), plus this generally seems to be the way to go with julia 1.0.
I left the old constructors in there for now because I don't have a good understanding who is using this stuff and what else might need to be updated. Someone else with a better overview of the situation can deprecate them formally in a new PR :)
Would be great if we could merge and tag this so that I can move on with the TextParse.jl PR.
@shashi, can you review this? I believe you wrote the original code?

Add StringArray constructors that take undef

---

src/WeakRefStrings.jl

This builds on top of #48 but deprecates all the old constructors. With this PR checked out I have IndexedTables and JuliaDB tests passing locally.

Finish #48: switch to Julia 1.0 constructors

---

src/WeakRefStrings.jl

Used notably by Tables.jl.
x-ref https://github.com/JuliaData/WeakRefStrings.jl/pull/50 and https://github.com/JuliaData/WeakRefStrings.jl/pull/48.

Add deprecation for StringVector(::Int) constructor

---

src/WeakRefStrings.jl
test/runtests.jl

fixes #55 
```julia
julia> @btime cmp($(sa[1]), $(sa[2]))
5.647 ns (0 allocations: 0 bytes)
-1
```
Much better now.
Also uses this to optimize `sort` and `sortperm` on `StringArray{String}` avoiding allocation before `cmp`

optimize cmp

---

Project.toml
src/WeakRefStrings.jl
src/inlinestrings.jl
test/inlinestrings.jl
test/runtests.jl

As frequently discussed recently, this PR introduces a new abstract type
`InlineString`, with concrete subtypes of specific sizes
(`InlineString3`, `InlineString7`, etc.). We support sizes 1 - 255
codeunit strings to be stored inline in these custom string types. In
this PR, I've implemented the full string interface for these types,
with performance that is as-good or better in all cases I checked.
Differences from the ShortStrings.jl package include:
* Different internal representation; each `InlineString` is a
`primitive type` directly, with no fields, but carries the string byte
bits directly; it relies on integer intrinsic functions directly,
which translate well for any size primitive type and the fact that
these inline strings operate very closely to actual unsigned integers
in a …

Introduce new stack-friendly InlineString types

---

Project.toml
src/inlinestrings.jl
test/inlinestrings.jl

Solves the ambiguity reported in https://discourse.julialang.org/t/having-trouble-implementating-a-tables-jl-row-table-when-using-badukgoweiqitools-dataframe-tbl-no-longer-works/63622
cc @xiaodaigh
I have a feeling that one is not mean to define `promote_type` directly.
(Will be making a PR to Julia to document that and then find out if i am wrong via Cunningham's law)

use promote_rule not promote_type

---

src/inlinestrings.jl
test/inlinestrings.jl

The issue in the optimized InlineString constructor that took a byte
buffer, byte position, and length was that it assumed it always had
`sizeof(T)` number of bytes it could "reinterpret" as an InlineString,
fiddle the bits and return a valid `T`. But if we're near the end of the
byte buffer, where we're trying to construct a final `InlineString7`,
for example, from the last 5 bytes of the buffer, it's invalid to use
our `unsafe_load` trick because we're reaching past the end of the byte
buffer to reinterpret memory. We already have safe-guards to zero out
that memory when constructing the actual InlineString, but if the byte
buffer doesn't happen to be aligned just right, or we're constructing an
`InlineString255` for example, it's very possible to get a segfault by
touching invalid …

Be more careful about InlineString creation from memory

---

Project.toml
src/WeakRefStrings.jl
src/inlinestrings.jl
test/inlinestrings.jl
test/runtests.jl

Fixes #81. Also removes the need for explicit serialization overloads.
The only hesitation in this approach was the difference from how regular
Strings work, but the Base docs are pretty clear that read/write are for
the "binary" layout of types, while `print` is for a textual
representation.

Define read/write on binary format of InlineStrings

---

Project.toml
README.md
src/inlinestrings.jl
test/inlinestrings.jl

Fixes https://github.com/JuliaData/WeakRefStrings.jl/issues/85
CC @quinnj

add String[X] types

---

src/poslenstrings.jl
test/poslenstrings.jl

Fixes the type instability issue mentioned in
https://github.com/JuliaData/InlineStrings.jl/issues/2.

Ensure string(::PosLenString) returns String

---

src/WeakRefStrings.jl
test/runtests.jl

The `AbstractArray` fallback for `Base.isassigned` relies on a `try`/`catch` and is unbelievably slow.
This PR adds a method for `StringArray` to avoid this along with some tests.

added isassigned method for StringArray to avoid disastrous try/catch fallback

---

.gitignore
src/WeakRefStrings.jl
test/runtests.jl

- No functional changes
- I was just auditting which packages depend on Parsers.jl directly, and it took me a while to see how this package was using it

Make clear Parsers.jl only required for PosLen
